### ISSUE TITLE
Give use cases to understand the features better

### ISSUE THREAD

**Issue by hansbogert** [Netflix/Fenzo#44]
After reading the _features_ I'm struggling to understand what actual use cases are where Fenzo comes in. For example in my case, I have a Spark framework (on Mesos) which runs interactive queries with a measured average response time. Now if I increase the cluster resources by a factor 2 or 4 for example, and increase the amount of Spark frameworks by that same factor, the variance increases greatly. So far, I can see that this stems from the fact that a Spark framework is very greedy; if a resource offer is made, the framework accepts all, and in the meantime other frameworks stall. The average response time is pretty much the same only because the added resources make up for the longer waiting periods for the frameworks. But the higher variance makes this unfavorable to interactive Spark sessions.

- Are there mechanisms/features in Fenzo which can help with this above problem? (Basically QoS problems, which Mesos doesn't seem to care about)
- Is anybody working on Spark/Fenzo integration? If not, does anyone have an idea about caveats/hurdles to implement it?

**Comment by spodila** [comment]
Fenzo caters to the needs of a Mesos framework for advanced scheduling optimizations and cluster autoscaling, see this [blog](http://techblog.netflix.com/2015/08/fenzo-oss-scheduler-for-apache-mesos.html) for an overview. 

What you are describing seems to be a case of multiple frameworks in a Mesos cluster, where one or more of them can starve for resources if another framework hoards (or has used up) all of the offers. That may require a solution in Mesos itself (just as an example, some way of fair sharing plus preemptions). Or, a single Spark framework may be able to achieve such fair share among its various Spark jobs instead of having one framework per job. Although, I am not as knowledgeable about Spark framework to say how feasible that is. Fenzo can be useful for such a framework in terms of optimizing task placements. However, preemptions and fair share concepts are not available in Fenzo yet.

**Comment by hansbogert** [comment]
Ok, thanks. Exactly what I needed to hear.
