### ISSUE TITLE
Interaction between frameworks using Fenzo

### ISSUE THREAD

**Issue by chogeek** [Netflix/Fenzo#51]
We have multiple Mesos frameworks in a Mesos Cluster with three hosts(agents). Some of the frameworks developed by ourselves are using Fenzo and some of the frameworks are not using Fenzo (e.g. Marathon). We have configured leaseOfferExpirySecs to 2 and have found that frameworks that use Fenzo have been starving frameworks that do not use Fenzo.
We would like to ask the following questions.

1. Can we have more than one Fenzo TaskSchduler in a Mesos Cluster?
2. Can we have Mesos Framework that uses Fenzo and Mesos Framework that does not use Fenzo in a Mesos Cluster?
3. Can we use Fenzo in a small cluster with three hosts(agents)?

**Comment by spodila** [comment]
Hello chogeek, Fenzo will be rejecting leases based on the configured leaseOfferExpirySecs. We see offers being rejected in our framework. Can you confirm if you are seeing the rejections at all or not? 
In the mean time, I will test multi-framework setup a little bit more with three hosts as you have it.

**Comment by spodila** [comment]
Can you confirm that your framework calls Fenzo's TaskScheduler.scheduleOnce(...) periodically? Even if there are no tasks to schedule? This is important because Fenzo does not create its own threads for taking actions such as releasing/rejecting offers after the timeout, or autoscaling. These actions are performed at the end of the scheduleOnce(), before the results are returned. With each call to scheduleOnce(), you should also send in any new offers obtained from Mesos.

I have created a test program that shows that Fenzo does release offers after the expiration time (2s in your example). See that example code here: https://gist.github.com/spodila/ea293a8974a557d8a7c8

Let me know if this addresses the issue.

**Comment by spodila** [comment]
Also, upgrade to fenzo-core 0.7.12 for a fix I just made for offer expiry not happening right in certain scenarios. See issue #50 for details.

**Comment by chogeek** [comment]
HI @spodila, thank you for your reply.

I confirm that our framework calls Fenzo's TaskScheduler.scheduleOnce(...) periodically in a thread like SampleFramework of Fenzo. And I see that Fenzo declines offer according to leaseOfferExpirySecs configuration.

What I want to know is that whether we can have multiple framework that uses Fenzo in a Mesos cluster. Each fenzo-enabled framework hold offer for a period of time for bin packing and auto scaling. If there are quite a lot of frameworks using Fenzo in a cluster, then resource circulation will become very slow. Should we have only one Fenzo framework in a cluster and all tasks should be submitted to that framework for bin packing and auto scaling purpose?

Moreover, since resource circulation is slowed down, frameworks that does not use Fenzo (e.g. Marathon) may take longer time in order to get resource. Should we have Mesos Framework that uses Fenzo and Mesos Framework that does not use Fenzo in a Mesos Cluster?

**Comment by spodila** [comment]
Let me try to address all of the questions you bring up. Do note that we currently run only one framework in our cluster.

- Resource circulation becoming slow
  With Fenzo you have full control of how many offers to reject and how often. In 0.7.12 we added some additional parameters you can set to TaskScheduler.Builder. So, there should be no fear of such a slow down.

- Bin packing
  Ideally, bin packing is done by one framework. If that one framework used Fenzo, then this is a solved problem.
  However, you can achieve good results with multiple frameworks if the allocator can send as much as possible entire resources of a host in the offer. That is, if there are two hosts and two frameworks, send one offer of entire host A to framework1 and another offer of entire host B to framework 2, instead of, two offers each to both frameworks, where each offer contains half the resources of a host. But, Mesos allocator does not do this, as far as I know.
  Next best with multiple frameworks would be if each framework knows not only the resources offered from a host, but, also what resources were not offered from that host. This information would help do smarter bin packing with limited information.
  You can "fake" the last point above by making the mesos-slave cmdline pass in custom attributes that indicate the total resources on the host.

- Autoscaling the cluster
  Multiple frameworks trying to autoscale can step on each other. Scaling up is easy, they each scale up only upto the amount of resources they need. However, scaling down will need coordination so a framework won't terminate a host that might be running tasks from another scheduler. If you can perform such coordination for scale down, then things could work. Additional thought may be needed here.

- Resource starvation
  Frameworks/schedulers that don't use Fenzo are not going to starve for resources due to Fenzo. Especially since you can totally control the offer rejection frequency. 
  However, resource starvation is common in Mesos when running with multiple frameworks. This is not specific to the use of Fenzo. A framework can run tasks on all hosts of a cluster when no other framework has any tasks. Later when another framework has tasks to run, it will starve for resources until one or more of the original framework's tasks complete. 
  Dynamic reservations, quotas, and the older reservations are used for such scenarios. However, they mostly works by fragmenting the cluster and thereby lowering possible utilization. Solutions for this are currently incomplete.

I hope this gives you a few things to think about. I am glad to answer any further questions.

**Comment by chogeek** [comment]
Hi @spodila,

Thank you for giving us insights about Fenzo and Mesos framework scheduling.

I agree with you that configuration parameters of Fenzo and Mesos do play an important role of resource scheduling.
Also, it is related to resource available in a cluster and amount of resource consumed by a framework.

I found that DRF algorithm of default Mesos allocator giving higher priority to frameworks consuming less resource.
We have quite a lot of tasks running using Marathon so it has to take longer time in order to get offer, regardless of the presence of framework using Fenzo.

**Comment by DavidMGross** [comment]
Might some of this be good to incorporate into the documentation?

**Comment by spodila** [comment]
@DavidMGross Incorporating these into the documentation sounds like a good idea. I am not sure yet which section it would go into and how to present this information. I feel like the comments are informal and span the areas of "Fenzo user doc", "best practices with frameworks using Fenzo", "mixing Fenzo frameworks with non-Fenzo frameworks", "known limitations and/or resource starvation with Mesos DRF", etc. 
Do you have any thoughts on how to structure these comments in to the docs?
