### ISSUE TITLE
Hard time limit on holding offers for Fenzo

### ISSUE THREAD

**Issue by dgrnbrg** [Netflix/Fenzo#57]
Currently, Fenzo supports releasing offers at a fixed rate. In order to have a Fenzo-scheduled framework function in a multiframework environment, it's important for every offer to be declined in a timely manner if it isn't used. For example, another framework may have specific constraints or properties it's looking for in an agent--currently, it's possible for Fenzo to hold onto an offer for many minutes (if you're unlucky on a very large cluster). This can negatively impact other frameworks that are looking for very specific hosts.

The solution I'd like to see is the ability to configure a maximum time to hold an offer before declining it; this way, a Fenzo-based framework could choose to hold no offers for longer than 30 seconds; this would greatly benefit multi-framework Mesos clusters.

**Comment by spodila** [comment]
@dgrnbrg it turns out you can achieve this already by setting the maximum offers to reject to a large number. That is, effectively telling Fenzo to not limit the number of offers to reject upon offer expiry. Here's one way to set the maximum to a large number:

``` java
final TaskScheduler scheduler = new TaskScheduler.Builder()
                .withLeaseRejectAction(new Action1<VirtualMachineLease>() {
                    @Override
                    public void call(VirtualMachineLease virtualMachineLease) {
                        ...
                    }
                })
                .withLeaseOfferExpirySecs(leaseExpirySecs)
                .withMaxOffersToReject(Integer.MAX_VALUE)
                .build();
```

Fenzo will then reject all leases whose offered time is more than leaseExpirySecs seconds ago.

However, note that the action to check which offers to reject is carried out only at the end of TaskScheduler.scheduleOnce() method. So you must routinely call that method for offers to expire timely. 

I will enhance documentation to make this clearer.

Does this work for you?

**Comment by dgrnbrg** [comment]
That should work, thanks! I wonder if there's benefit in making rejecting all offers into another builder method, vs. requiring the user to treat it as a special case of the rejection logic. Either way, that will solve the problem.

**Comment by spodila** [comment]
Fenzo 0.8.2 has a new convenience mthod in the builder, withRejectAllExpiredOffers(), for this.

**Comment by dgrnbrg** [comment]
Thank you!
