### ISSUE TITLE
Lease expiration v.s. scale up trigger

### ISSUE THREAD

**Issue by yanglei99** [Netflix/Fenzo#74]
Thanks Fenzo for the separation of concerns to abstract the scheduling logic.  I was able to create a simple framework (using Fenzo) to scale up/down tasks(Docker) and also scale up/down platform (Softlayer) as needed.

One issue I faced is to balance between a shorter offer expiration (to increase platform sharing) and less aggressive scale up trigger (due to offer just expired ). 

Finally the solution is, besides setting offer expiration and scale up delay configuration, I also add another configuration of "wait seconds since last lease expiration before scale up" to ignore the scale up if the last offer expiration is within a duration.  

Please let me know if there are other alternatives than introducing this new configuration. You can find out details of my framework here: https://github.com/yanglei99/Mesos_Auto_Scale

Thanks.

**Comment by spodila** [comment]
Nice work. Glad to note Fenzo was useful for your framework.

Did you use the TaskScheduler.Builder.withDelayAutoscaleUpBySecs(secs) to make the scale up less aggressive? We introduced that for very similar reasons. You should not need to introduce the new delay you are referring to after the last offer expiration. The JavaDocs for that builder method has additional explanation on why and what to set the delay to. I realized the JavaDocs links weren't updated to the latest ones, I will do that shortly. You can see the java docs in the code [here](https://github.com/Netflix/Fenzo/blob/master/fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java#L312).

I notice in your code that you introduced a similar delay to scale down outside Fenzo. You can use TaskScheduler.Builder.withDelayAutoscaleDownBySecs(secs) for that. When Fenzo gives a call back for scale down, it disables those hosts internally before the call back, for a time equivalent to the configured cool down seconds for the AutoScale rule. If you further delay the scale down, the hosts for which Fenzo called the scale down action will not be used until the cooldown period expires. So effectively, you have fewer servers to assign resources from. 

I suggest you use the built in auto scale delay feature. 

Also, since you are using the auto scaling feature, it would be useful for you to use bin packing as the fitness calculator (e.g., BinPackingFitnessCalculators.cpuMemNetworkBinPacker) when building the scheduler. 

Let me know if you find these don't work for you. My understanding is that they should.

**Comment by spodila** [comment]
@yanglei99 The java docs are now updated. You can see the scale up delay doc [here](http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/TaskScheduler.Builder.html#withDelayAutoscaleUpBySecs-long-).

Let me know if you need any further info.

**Comment by yanglei99** [comment]
@spodila, Thanks! Will follow your suggestions and let you know the result.

**Comment by spodila** [comment]
@yanglei99 Do you still need this issue open?

**Comment by spodila** [comment]
@yanglei99 I am going to close this issue since there doesn't seem to be an open question after the last discussion. Do open a new one if you have a follow up. Thank you.
